Added options to chkdif

diff --git a/chkdif b/chkdif
--- a/chkdif
+++ b/chkdif
@@ -4,13 +4,29 @@
 # Simple script for checking for differences between two files
 # Usage: chkdif <file1> <file2>
 
+OPT=""
+while getopts ":ys" opt; do
+	case ${opt} in
+		y ) OPT="$OPT --side-by-side"
+			;;
+		s ) OPT="$OPT --suppress-common-lines"
+			;;
+		\? ) echo "Error: Invalid option passed"
+		     echo "Usage: chkdif [-s][-y] <file1><file2>"
+		     exit 1
+			;;
+	esac
+done
+
+shift $((OPTIND - 1))
 if [ $# -lt 2 ]
 then
-	echo "Usage: chkdif <file1> <file2>"
+	echo "Error: Insufficient files for comparison"
+	echo "Usage: chkdif [options] <file1> <file2>"
 	exit 1
 fi
 
-CMD=$(diff --suppress-common-lines --side-by-side $@)
+CMD=$(diff $OPT $@)
 
 if [ -z "$CMD" ]
 then
